---
- name: Listen for events on a webhook
  hosts: all

  sources:
   - ansible.eda.webhook:
       host: 0.0.0.0
       port: 5000

  rules:

   - name: Handle Red Hat Insights event
     condition: event.payload is defined

     action:
        run_job_template:
          name: Slack_Message
          post_events: true
          organization: Default
          job_args:
            extra_vars:
              my_payload: "{{ event.payload }}"


   - name: Action taken now display as resolved 
     condition: event.passed_once is defined
     action:  
      run_job_template:
        name: Issue_Resolved
        organization: Default
